#ifndef __IMAGE_MANAGER_H__
#define __IMAGE_MANAGER_H__

#include"const.h"

struct ImageInfo
{
	// DrawGraph等で使用する実際の画像番号
	int imageHandle;
	// 画像ファイルの場所(フォルダ名・ファイル名を含む)
	const char* imagePath;
};

class ImageManager
{
private:
	ImageManager();
	ImageManager& operator = (ImageManager& other) = delete;
	ImageManager(const ImageManager& other) = delete;
	 ImageInfo imageInfoArray[IMAGE_INFO_LENGTH];

public:
	enum IMAGENAME
	{
		IMAGE_PLAYER_LEFT_IDLE,
		IMAGE_PLAYER_LEFT_WIN,
		IMAGE_PLAYER_LEFT_RELOAD,
		IMAGE_PLAYER_LEFT_SHOOT,
		IMAGE_PLAYER_LEFT_FAILED,
		IMAGE_PLAYER_LEFT_OVER,
		

		IMAGE_PLAYER_RIGHT_IDLE,
		IMAGE_PLAYER_RIGHT_WIN,
		IMAGE_PLAYER_RIGHT_CRANK,
		IMAGE_PLAYER_RIGHT_OVER,

		IMAGE_BG,
		IMAGE_NUMBER,
		IMAGE_LAUNCH_PAD_1,
		IMAGE_LAUNCH_PAD_2,
		IMAGE_LAUNCH_PAD_3,
		IMAGE_LAUNCH_PAD_4,
		IMAGE_LAUNCH_PAD_5,
		IMAGE_LAUNCH_PAD_6,
		IMAGE_LAUNCH_PAD_7,
		IMAGE_LAUNCH_PAD_8,
		IMAGE_LAUNCH_PAD_9,
		IMAGE_LAUNCH_PAD_10,
		IMAGE_LAUNCH_PAD_11,
		IMAGE_LAUNCH_PAD_12,
		IMAGE_CRANK,
		IMAGE_PIPE,
		IMAGE_ARROW,

		IMAGE_BUBBLE_BLUE,
		IMAGE_BUBBLE_BLUE_BURST_1,
		IMAGE_BUBBLE_BLUE_BURST_2,
		IMAGE_BUBBLE_BLUE_BURST_3,
		IMAGE_BUBBLE_BLUE_BANISH,
		IMAGE_BUBBLE_BLUE_ENEMY,

		IMAGE_BUBBLE_RED,
		IMAGE_BUBBLE_RED_BURST_1,
		IMAGE_BUBBLE_RED_BURST_2,
		IMAGE_BUBBLE_RED_BURST_3,
		IMAGE_BUBBLE_RED_BANISH,
		IMAGE_BUBBLE_RED_ENEMY,

		IMAGE_BUBBLE_PURPLE,
		IMAGE_BUBBLE_PURPLE_BURST_1,
		IMAGE_BUBBLE_PURPLE_BURST_2,
		IMAGE_BUBBLE_PURPLE_BURST_3,
		IMAGE_BUBBLE_PURPLE_BANISH,
		IMAGE_BUBBLE_PURPLE_ENEMY,

		IMAGE_BUBBLE_GRAY,
		IMAGE_BUBBLE_GRAY_BURST_1,
		IMAGE_BUBBLE_GRAY_BURST_2,
		IMAGE_BUBBLE_GRAY_BURST_3,
		IMAGE_BUBBLE_GRAY_BANISH,
		IMAGE_BUBBLE_GRAY_ENEMY,

		IMAGE_BUBBLE_YELLOW,
		IMAGE_BUBBLE_YELLOW_BURST_1,
		IMAGE_BUBBLE_YELLOW_BURST_2,
		IMAGE_BUBBLE_YELLOW_BURST_3,
		IMAGE_BUBBLE_YELLOW_BANISH,
		IMAGE_BUBBLE_YELLOW_ENEMY,

		IMAGE_BUBBLE_GREEN,
		IMAGE_BUBBLE_GREEN_BURST_1,
		IMAGE_BUBBLE_GREEN_BURST_2,
		IMAGE_BUBBLE_GREEN_BURST_3,
		IMAGE_BUBBLE_GREEN_BANISH,
		IMAGE_BUBBLE_GREEN_ENEMY,

		IMAGE_BUBBLE_ORANGE,
		IMAGE_BUBBLE_ORANGE_BURST_1,
		IMAGE_BUBBLE_ORANGE_BURST_2,
		IMAGE_BUBBLE_ORANGE_BURST_3,
		IMAGE_BUBBLE_ORANGE_BANISH,
		IMAGE_BUBBLE_ORANGE_ENEMY,

		IMAGE_BUBBLE_WHITE,
		IMAGE_BUBBLE_WHITE_BURST_1,
		IMAGE_BUBBLE_WHITE_BURST_2,
		IMAGE_BUBBLE_WHITE_BURST_3,
		IMAGE_BUBBLE_WHITE_BANISH,
		IMAGE_BUBBLE_WHITE_ENEMY,


		IMAGE_MAX,
	};

	static ImageManager* getInstance();

	void initImageManager();
	bool setImageInfo(int imageId, const char* imagePath);
	void loadImageAll();
	int getImageHandle(int imageId);
	void clearImageManager();
};



#endif